# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fa6bfab7732a2416d88fd9a5294d3c0d291a3294780ab0a03a67083e798372f33047350549c296710e2747a69986c89234563d1e2036d5587d6caa504981e05

test:
  secret_key_base: 215e6b77f1347f381d903cfe88ac97a1dfb257eca1e3007fe8b052d980ba952df810eed679781edd1e7f958f0a2127abe3d7ff92e5f5b78a15cf0a94e77583a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
